# Generated by Django 3.0.8 on 2021-07-02 02:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210701_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_code', validators=[accounts.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepics', validators=[accounts.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='codinglinks',
            name='image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
