# Generated by Django 3.0.3 on 2021-07-03 08:33

import accounts.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210701_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='education',
            name='qualif',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='github',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IN'),
        ),
        migrations.AddField(
            model_name='account',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='qr_code', validators=[accounts.models.validate_image]),
        ),
        migrations.AddField(
            model_name='education',
            name='grade_points',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='highest_degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelor'), ('Masters', 'Master'), ('Diploma', 'Diploma'), ('B.Pharm', 'B.Pharm'), ('Pharm.D', 'Pharm.D'), ('Degree', 'Degree'), ('HighSchool', 'Highschool')], default='highschool', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='codinglinks',
            name='image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
